

### GET ALL Products
GET http://localhost:3000/products/

### GET ONLY ONE 
GET http://localhost:3000/products/674fdca551bb01cd18b782ab

### CREATE NEW PRODUCT
POST http://localhost:3000/products/
content-type: application/json

{
    "name": "Phone",
    "description": "Phone last Generation.",
    "category": "Electronics",
    "price": -129.99,
    "stockQuantity": 100,
    "weight": 10,
    "isActive": true
}

### UPDATE PRODUCT
PUT http://localhost:3000/products/674fdca551bb01cd18b782ab
content-type: application/json

{
    "name": "Phone Xiaomi Redmi Note 13",
    "description": "Phone last Generation, model 2024.",
    "category": "Electronics",
    "price": 119.99,
    "stockQuantity": 150,
    "weight": 0.5,
    "isActive": true
}

### DELETE PRODUCT
DELETE http://localhost:3000/products/674fd31773d1817d7793c639




### GET ALL REVIEWS FOR A SPECIFIC PRODUCT
GET http://localhost:3000/reviews/product/674e4b4df63c9c3ea101c26a


### GET REVIEW BY ID
GET http://localhost:3000/reviews/674f2b24f63c9c3ea101cc2e


###  CREATE A NEW REVIEW
POST http://localhost:3000/reviews/
content-type: application/json

{
  "userId": "user43",
  "productId": "674e4b4df63c9c3ea101c26a",
  "rating": 5,
  "reviewText": "Fantastic",
  "createdAt": "2024-12-03T12:00:00Z"
}

### UPDATE REVIEW
PUT http://localhost:3000/reviews/674fd00634050a3423ed1e91
content-type: application/json

{
  "userId": "user459",
  "productId": "674e4b4df63c9c3ea101c26a",
  "rating": 4,
  "reviewText": "Fantastic2",
  "createdAt": "2024-12-03T12:00:00Z"
}

### DELETE REVIEW
DELETE http://localhost:3000/reviews/674fd1e134050a3423ed1e92




### GET ALL Products ON RENDER
GET https://cse341-project2-5fyz.onrender.com/products/

### CREATE NEW PRODUCT ON RENDER
POST https://cse341-project2-5fyz.onrender.com/products/
content-type: application/json

{
    "name": "aaaaa",
    "description": "Phone last Generation.",
    "category": "Electronics",
    "price": 129.99,
    "stockQuantity": 150,
    "weight": 0.4,
    "isActive": true
}


### GET ALL REVIEWS FOR A SPECIFIC PRODUCT ON RENDER
GET https://cse341-project2-5fyz.onrender.com/reviews/product/674e4b4df63c9c3ea101c26a


### GET REVIEW BY ID ON RENDER
GET https://cse341-project2-5fyz.onrender.com/674f2b24f63c9c3ea101cc2e


###  CREATE A NEW REVIEW ON RENDER
POST https://cse341-project2-5fyz.onrender.com/reviews/
content-type: application/json

{
  "userId": "user43",
  "productId": "674e4b4df63c9c3ea101c26a",
  "rating": 5,
  "reviewText": "Fantastic",
  "createdAt": "2024-12-03T12:00:00Z"
}